n=[1,2,3,4,5,8,2,23,0]
n.append(200)#THE apopend FUN CAN CHANGE THE LAST VALUE OF A LIST
print(n)
n.insert(1,23)#THIS FUN TAKE 2 ARGUMENTS INDEX AND TARGET NUMBER AND INSERT THE NO INTO THE FIXED INDEX
print(n)
n.remove(23),n.remove(1)#THIS FUN CAN REMOVE THE PASSED VALUE IN THE LIST
print(n)
n.pop()#THIS CAN SIMPLY REMOVE THE LAST INDEX IN THE LIST
print(n)
n.index(2)#IT JUST SHOWS THE PASSED ARGUMENT'S INDEX IN THE LIST n
print(n)
print(2 in n)#IT RETURNS THE BOOLEAN VALUE IT JUST CHECKS THE NUMBER IN LIST# .count(2)
print(n.count(2))#IT COUNTS HOW MANY NUMBRERS ARE THE GIVEN IN LISTS
n.sort()#IT JUST MAKE ALL THE VALUE INTO ASCENDING ORDER
print(n)
n.reverse()#IT JUUST REVRSE THE GIVEN VALUE
print(n)
  