#EXAMOLE CODE FOR MATH FUNCTIONS
q=-2.5
print(round(q))#ROUND MAKES THE ENACT ROUNDOFF VALUE
print(abs(q))# IT GIVES THE ABSOLUTE VALUE IGNORES NEGATIVITY
import math
print((math.ceil(q)))#SHOWS THE CEILING OF THE NO
print((math.floor(q)))#SHOWS THE NEXT NEAREST NO